import re
import logging
import pdfplumber
from typing import List, Dict

logger = logging.getLogger('pdf_parser_service')

def parse_mcqs_from_pdf(pdf_path: str) -> List[Dict]:
    """
    Parse MCQs from a PDF file generated by the system
    """
    mcqs = []
    current_mcq = {}
    
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                text = page.extract_text()
                if not text:
                    continue
                
                lines = text.split('\n')
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    
                    # Detect question pattern
                    question_match = re.match(r'Question\s+(\d+):\s*\[BL-(\d+):\s*([^\]]+)\]\s*(.*)', line)
                    if question_match:
                        # Save previous question if exists
                        if current_mcq:
                            mcqs.append(current_mcq)
                            current_mcq = {}
                        
                        # Start new question
                        current_mcq = {
                            'question_number': int(question_match.group(1)),
                            'blooms_level': question_match.group(2),
                            'blooms_category': question_match.group(3),
                            'question': question_match.group(4).strip(),
                            'options': [],
                            'correct_answer': None
                        }
                        continue
                    
                    # Detect options section
                    if line.lower() == 'options:' and current_mcq:
                        current_mcq['reading_options'] = True
                        continue
                    
                    # Detect individual options (A), B), etc.)
                    option_match = re.match(r'([A-D])\)\s*(.*)', line)
                    if option_match and current_mcq.get('reading_options'):
                        option_letter = option_match.group(1)
                        option_text = option_match.group(2).strip()
                        current_mcq['options'].append({
                            'letter': option_letter,
                            'text': option_text
                        })
                        continue
                    
                    # Detect correct answer
                    correct_match = re.match(r'Correct Answer:\s*([A-D])', line, re.IGNORECASE)
                    if correct_match and current_mcq:
                        current_mcq['correct_answer'] = correct_match.group(1).upper()
                        current_mcq['reading_options'] = False
                        continue
        
        # Add the last question if exists
        if current_mcq:
            mcqs.append(current_mcq)
            
        logger.info(f"Successfully parsed {len(mcqs)} MCQs from PDF")
        return mcqs
        
    except Exception as e:
        logger.error(f"Error parsing PDF: {str(e)}", exc_info=True)
        return []